--- 
:type: widget
:name: app:pagination
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ pagination ]
:description: "app:pagination is a control for assisting in pagination capabilities using messages"
