// _ModuleDocument_EOArchive_English.java
// Generated by EnterpriseObjects palette at Sunday, November 6, 2005 12:13:43 PM US/Eastern

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ModuleDocument_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    ArrayController _arrayController0, _arrayController1, _arrayController2, _arrayController3, _arrayController4, _arrayController5;
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector2;
    ObjectController _objectController0;
    TreeController _treeController0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1, _eoFrame2;
    com.webobjects.eointerface.swing.EOTable _nsOutlineView0, _nsTableView0, _nsTableView1, _nsTableView2, _nsTableView3, _nsTableView4, _nsTableView5;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn10, _eoTableColumn11, _eoTableColumn12, _eoTableColumn13, _eoTableColumn14, _eoTableColumn15, _eoTableColumn16, _eoTableColumn17, _eoTableColumn2, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7, _eoTableColumn8, _eoTableColumn9;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsSearchField0, _nsSearchField1, _nsSearchField2, _nsSearchField3, _nsTextField0, _nsTextField1, _nsTextField2, _nsTextField3;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox10, _nsBox11, _nsBox12, _nsBox13, _nsBox14, _nsBox15, _nsBox16, _nsBox17, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsBox8, _nsBox9;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton10, _nsButton11, _nsButton12, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JCheckBox _jCheckBox0, _jCheckBox1, _jCheckBox2;
    javax.swing.JPanel _nsView0, _nsView1, _nsView2;

    public _ModuleDocument_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _jCheckBox2 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");
        _objectController0 = (ObjectController)_registered(new ObjectController(), "Module Controller");
        _jCheckBox1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");
        _jCheckBox0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");
        _arrayController5 = (ArrayController)_registered(new ArrayController(), "Page Array Controller");
        _nsSearchField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTableColumn17 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn16 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn15 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _nsTableView5 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        _nsButton12 = (javax.swing.JButton)_registered(new javax.swing.JButton("Add"), "");
        _arrayController4 = (ArrayController)_registered(new ArrayController(), "Shared Instance Config Array Controller");
        _nsButton11 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove"), "");
        _nsBox17 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox16 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _eoFrame2 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Shared Instance Inspector");
        _nsView2 = (JPanel)_eoFrame2.getContentPane();
        _nsSearchField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTableColumn14 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn13 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn12 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _nsTableView4 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        _nsButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton("Add"), "");
        _arrayController3 = (ArrayController)_registered(new ArrayController(), "Page Instance Binding Options");
        _nsButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove"), "");
        _nsBox15 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox14 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _eoTableColumn11 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn10 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn9 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn8 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _nsTableView3 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        _nsButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("Add"), "");
        _arrayController2 = (ArrayController)_registered(new ArrayController(), "Page Instance Bindings");
        _nsButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove"), "");
        _nsBox13 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox12 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _nsTableView2 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("Add"), "");
        _arrayController1 = (ArrayController)_registered(new ArrayController(), "Page Instance Configs");
        _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove"), "");
        _nsBox11 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox10 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("-"), "");
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("+>"), "");
        _treeController0 = (TreeController)_registered(new TreeController(), "Page Instances Hierarchy");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("+"), "");
        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _nsOutlineView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        _nsBox9 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Page Instances Inspector");
        _nsView1 = (JPanel)_eoFrame1.getContentPane();
        _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsSearchField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsSearchField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Add"), "");
        _arrayController0 = (ArrayController)_registered(new ArrayController(), "Shared Instance Array Controller");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove"), "");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Module Main Window");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_eoFrame0, _owner(), "delegate");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_jCheckBox2, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_jCheckBox1, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_jCheckBox0, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_nsSearchField3, "Lucida Grande", 13, Font.PLAIN);
        _nsSearchField3.setEditable(true);
        _nsSearchField3.setOpaque(true);
        _nsSearchField3.setText("");
        _nsSearchField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsSearchField3.setSelectable(true);
        _nsSearchField3.setEnabled(true);
        _eoTableColumn17.setMinWidth(12);
        _eoTableColumn17.setMaxWidth(67);
        _eoTableColumn17.setPreferredWidth(16);
        _eoTableColumn17.setWidth(16);
        _eoTableColumn17.setResizable(true);
        _eoTableColumn17.setHeaderValue("""");
        if ((_eoTableColumn17.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn17.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn16.setMinWidth(33);
        _eoTableColumn16.setMaxWidth(1000);
        _eoTableColumn16.setPreferredWidth(216);
        _eoTableColumn16.setWidth(216);
        _eoTableColumn16.setResizable(true);
        _eoTableColumn16.setHeaderValue("Value");
        if ((_eoTableColumn16.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn16.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn15.setMinWidth(34);
        _eoTableColumn15.setMaxWidth(1000);
        _eoTableColumn15.setPreferredWidth(141);
        _eoTableColumn15.setWidth(141);
        _eoTableColumn15.setResizable(true);
        _eoTableColumn15.setHeaderValue("Name");
        if ((_eoTableColumn15.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn15.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView5.table().addColumn(_eoTableColumn15);
        _nsTableView5.table().addColumn(_eoTableColumn16);
        _nsTableView5.table().addColumn(_eoTableColumn17);
        _setFontForComponent(_nsTableView5.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView5.table().setRowHeight(20);
        _setFontForComponent(_nsButton12, "Lucida Grande", 13, Font.PLAIN);
        _nsButton12.setMargin(new Insets(0, 2, 0, 2));
        _nsButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController4, "add", _nsButton12), ""));
        _nsButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController4, "remove", _nsButton11), ""));
        _setFontForComponent(_nsButton11, "Lucida Grande", 13, Font.PLAIN);
        _nsButton11.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsBox17.getLayout() instanceof EOViewLayout)) { _nsBox17.setLayout(new EOViewLayout()); }
        _nsButton11.setSize(83, 26);
        _nsButton11.setLocation(245, 280);
        ((EOViewLayout)_nsBox17.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox17.add(_nsButton11);
        _nsButton12.setSize(83, 26);
        _nsButton12.setLocation(335, 280);
        ((EOViewLayout)_nsBox17.getLayout()).setAutosizingMask(_nsButton12, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox17.add(_nsButton12);
        _nsTableView5.setSize(400, 217);
        _nsTableView5.setLocation(14, 45);
        ((EOViewLayout)_nsBox17.getLayout()).setAutosizingMask(_nsTableView5, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox17.add(_nsTableView5);
        _nsSearchField3.setSize(182, 22);
        _nsSearchField3.setLocation(233, 15);
        ((EOViewLayout)_nsBox17.getLayout()).setAutosizingMask(_nsSearchField3, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox17.add(_nsSearchField3);
        if (!(_nsBox16.getLayout() instanceof EOViewLayout)) { _nsBox16.setLayout(new EOViewLayout()); }
        _nsBox17.setSize(428, 313);
        _nsBox17.setLocation(2, 15);
        ((EOViewLayout)_nsBox16.getLayout()).setAutosizingMask(_nsBox17, EOViewLayout.MinYMargin);
        _nsBox16.add(_nsBox17);
        _nsBox16.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Shared Instance Config", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsBox16.setSize(432, 330);
        _nsBox16.setLocation(10, 8);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsBox16, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView2.add(_nsBox16);
        _nsView2.setSize(452, 354);
        _eoFrame2.setTitle("Shared Instance Inspector");
        _eoFrame2.setLocation(669, 607);
        _eoFrame2.setSize(452, 354);
        _setFontForComponent(_nsSearchField2, "Lucida Grande", 13, Font.PLAIN);
        _nsSearchField2.setEditable(true);
        _nsSearchField2.setOpaque(true);
        _nsSearchField2.setText("");
        _nsSearchField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsSearchField2.setSelectable(true);
        _nsSearchField2.setEnabled(true);
        _eoTableColumn14.setMinWidth(12);
        _eoTableColumn14.setMaxWidth(67);
        _eoTableColumn14.setPreferredWidth(24);
        _eoTableColumn14.setWidth(24);
        _eoTableColumn14.setResizable(true);
        _eoTableColumn14.setHeaderValue("""");
        if ((_eoTableColumn14.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn14.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn13.setMinWidth(33);
        _eoTableColumn13.setMaxWidth(1000);
        _eoTableColumn13.setPreferredWidth(207);
        _eoTableColumn13.setWidth(207);
        _eoTableColumn13.setResizable(true);
        _eoTableColumn13.setHeaderValue("Value");
        if ((_eoTableColumn13.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn13.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn12.setMinWidth(34);
        _eoTableColumn12.setMaxWidth(1000);
        _eoTableColumn12.setPreferredWidth(156);
        _eoTableColumn12.setWidth(156);
        _eoTableColumn12.setResizable(true);
        _eoTableColumn12.setHeaderValue("Name");
        if ((_eoTableColumn12.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn12.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView4.table().addColumn(_eoTableColumn12);
        _nsTableView4.table().addColumn(_eoTableColumn13);
        _nsTableView4.table().addColumn(_eoTableColumn14);
        _setFontForComponent(_nsTableView4.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView4.table().setRowHeight(20);
        _setFontForComponent(_nsButton10, "Lucida Grande", 13, Font.PLAIN);
        _nsButton10.setMargin(new Insets(0, 2, 0, 2));
        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController3, "add", _nsButton10), ""));
        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController3, "remove", _nsButton9), ""));
        _setFontForComponent(_nsButton9, "Lucida Grande", 13, Font.PLAIN);
        _nsButton9.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsBox15.getLayout() instanceof EOViewLayout)) { _nsBox15.setLayout(new EOViewLayout()); }
        _nsButton9.setSize(83, 26);
        _nsButton9.setLocation(238, 149);
        ((EOViewLayout)_nsBox15.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox15.add(_nsButton9);
        _nsButton10.setSize(83, 26);
        _nsButton10.setLocation(328, 149);
        ((EOViewLayout)_nsBox15.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox15.add(_nsButton10);
        _nsTableView4.setSize(400, 120);
        _nsTableView4.setLocation(7, 11);
        ((EOViewLayout)_nsBox15.getLayout()).setAutosizingMask(_nsTableView4, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox15.add(_nsTableView4);
        _nsSearchField2.setSize(182, 22);
        _nsSearchField2.setLocation(233, -160);
        ((EOViewLayout)_nsBox15.getLayout()).setAutosizingMask(_nsSearchField2, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox15.add(_nsSearchField2);
        if (!(_nsBox14.getLayout() instanceof EOViewLayout)) { _nsBox14.setLayout(new EOViewLayout()); }
        _nsBox15.setSize(418, 182);
        _nsBox15.setLocation(2, 15);
        ((EOViewLayout)_nsBox14.getLayout()).setAutosizingMask(_nsBox15, EOViewLayout.MinYMargin);
        _nsBox14.add(_nsBox15);
        _nsBox14.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Page Instance Binding Options", true, "Lucida Grande", 11, Font.PLAIN));
        _eoTableColumn11.setMinWidth(85);
        _eoTableColumn11.setMaxWidth(1000);
        _eoTableColumn11.setPreferredWidth(88);
        _eoTableColumn11.setWidth(88);
        _eoTableColumn11.setResizable(true);
        _eoTableColumn11.setHeaderValue("Model Key Path");
        if ((_eoTableColumn11.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn11.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn10.setMinWidth(80);
        _eoTableColumn10.setMaxWidth(1000);
        _eoTableColumn10.setPreferredWidth(83);
        _eoTableColumn10.setWidth(83);
        _eoTableColumn10.setResizable(true);
        _eoTableColumn10.setHeaderValue("Controller Key");
        if ((_eoTableColumn10.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn10.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn9.setMinWidth(147);
        _eoTableColumn9.setMaxWidth(1000);
        _eoTableColumn9.setPreferredWidth(150);
        _eoTableColumn9.setWidth(150);
        _eoTableColumn9.setResizable(true);
        _eoTableColumn9.setHeaderValue("Bind To Shared Instance ID");
        if ((_eoTableColumn9.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn9.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn8.setMinWidth(75);
        _eoTableColumn8.setMaxWidth(1000);
        _eoTableColumn8.setPreferredWidth(79);
        _eoTableColumn8.setWidth(79);
        _eoTableColumn8.setResizable(true);
        _eoTableColumn8.setHeaderValue("Bind Property");
        if ((_eoTableColumn8.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn8.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView3.table().addColumn(_eoTableColumn8);
        _nsTableView3.table().addColumn(_eoTableColumn9);
        _nsTableView3.table().addColumn(_eoTableColumn10);
        _nsTableView3.table().addColumn(_eoTableColumn11);
        _setFontForComponent(_nsTableView3.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView3.table().setRowHeight(20);
        _setFontForComponent(_nsButton8, "Lucida Grande", 13, Font.PLAIN);
        _nsButton8.setMargin(new Insets(0, 2, 0, 2));
        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController2, "add", _nsButton8), ""));
        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController2, "remove", _nsButton7), ""));
        _setFontForComponent(_nsButton7, "Lucida Grande", 13, Font.PLAIN);
        _nsButton7.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsBox13.getLayout() instanceof EOViewLayout)) { _nsBox13.setLayout(new EOViewLayout()); }
        _nsButton7.setSize(83, 26);
        _nsButton7.setLocation(261, 120);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox13.add(_nsButton7);
        _nsButton8.setSize(83, 26);
        _nsButton8.setLocation(351, 120);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox13.add(_nsButton8);
        _nsTableView3.setSize(416, 91);
        _nsTableView3.setLocation(14, 11);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsTableView3, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox13.add(_nsTableView3);
        _nsBox14.setSize(422, 199);
        _nsBox14.setLocation(11, 138);
        ((EOViewLayout)_nsBox13.getLayout()).setAutosizingMask(_nsBox14, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox13.add(_nsBox14);
        if (!(_nsBox12.getLayout() instanceof EOViewLayout)) { _nsBox12.setLayout(new EOViewLayout()); }
        _nsBox13.setSize(446, 344);
        _nsBox13.setLocation(2, 15);
        ((EOViewLayout)_nsBox12.getLayout()).setAutosizingMask(_nsBox13, EOViewLayout.MinYMargin);
        _nsBox12.add(_nsBox13);
        _nsBox12.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Page Instance Bindings", true, "Lucida Grande", 11, Font.PLAIN));
        _eoTableColumn7.setMinWidth(12);
        _eoTableColumn7.setMaxWidth(67);
        _eoTableColumn7.setPreferredWidth(33);
        _eoTableColumn7.setWidth(33);
        _eoTableColumn7.setResizable(true);
        _eoTableColumn7.setHeaderValue("""");
        if ((_eoTableColumn7.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn7.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn6.setMinWidth(33);
        _eoTableColumn6.setMaxWidth(1000);
        _eoTableColumn6.setPreferredWidth(226);
        _eoTableColumn6.setWidth(226);
        _eoTableColumn6.setResizable(true);
        _eoTableColumn6.setHeaderValue("Value");
        if ((_eoTableColumn6.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn6.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn5.setMinWidth(34);
        _eoTableColumn5.setMaxWidth(1000);
        _eoTableColumn5.setPreferredWidth(144);
        _eoTableColumn5.setWidth(144);
        _eoTableColumn5.setResizable(true);
        _eoTableColumn5.setHeaderValue("Name");
        if ((_eoTableColumn5.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn5.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView2.table().addColumn(_eoTableColumn5);
        _nsTableView2.table().addColumn(_eoTableColumn6);
        _nsTableView2.table().addColumn(_eoTableColumn7);
        _setFontForComponent(_nsTableView2.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView2.table().setRowHeight(20);
        _setFontForComponent(_nsButton6, "Lucida Grande", 13, Font.PLAIN);
        _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController1, "add", _nsButton6), ""));
        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController1, "remove", _nsButton5), ""));
        _setFontForComponent(_nsButton5, "Lucida Grande", 13, Font.PLAIN);
        _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsBox11.getLayout() instanceof EOViewLayout)) { _nsBox11.setLayout(new EOViewLayout()); }
        _nsButton5.setSize(83, 26);
        _nsButton5.setLocation(261, 137);
        ((EOViewLayout)_nsBox11.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox11.add(_nsButton5);
        _nsButton6.setSize(83, 26);
        _nsButton6.setLocation(351, 137);
        ((EOViewLayout)_nsBox11.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox11.add(_nsButton6);
        _nsTableView2.setSize(416, 108);
        _nsTableView2.setLocation(14, 11);
        ((EOViewLayout)_nsBox11.getLayout()).setAutosizingMask(_nsTableView2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox11.add(_nsTableView2);
        if (!(_nsBox10.getLayout() instanceof EOViewLayout)) { _nsBox10.setLayout(new EOViewLayout()); }
        _nsBox11.setSize(446, 170);
        _nsBox11.setLocation(2, 15);
        ((EOViewLayout)_nsBox10.getLayout()).setAutosizingMask(_nsBox11, EOViewLayout.MinYMargin);
        _nsBox10.add(_nsBox11);
        _nsBox10.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Page Instance Config", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsButton4, "Lucida Grande", 10, Font.PLAIN);
        _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_treeController0, "remove", _nsButton4), ""));
        _setFontForComponent(_nsButton3, "Lucida Grande", 10, Font.PLAIN);
        _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_treeController0, "addChild", _nsButton3), ""));
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_treeController0, "add", _nsButton2), ""));
        _setFontForComponent(_nsButton2, "Lucida Grande", 10, Font.PLAIN);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _eoTableColumn4.setMinWidth(8);
        _eoTableColumn4.setMaxWidth(1000);
        _eoTableColumn4.setPreferredWidth(267);
        _eoTableColumn4.setWidth(267);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("Class");
        if ((_eoTableColumn4.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn4.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn3.setMinWidth(16);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(169);
        _eoTableColumn3.setWidth(169);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Instance ID");
        if ((_eoTableColumn3.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn3.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsOutlineView0.table().addColumn(_eoTableColumn3);
        _nsOutlineView0.table().addColumn(_eoTableColumn4);
        _setFontForComponent(_nsOutlineView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsOutlineView0.table().setRowHeight(20);
        if (!(_nsBox9.getLayout() instanceof EOViewLayout)) { _nsBox9.setLayout(new EOViewLayout()); }
        _nsOutlineView0.setSize(444, 129);
        _nsOutlineView0.setLocation(14, 46);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsOutlineView0, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsOutlineView0);
        _nsButton2.setSize(31, 26);
        _nsButton2.setLocation(11, 12);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsButton2);
        _nsButton4.setSize(31, 26);
        _nsButton4.setLocation(64, 12);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsButton4);
        _nsButton3.setSize(31, 26);
        _nsButton3.setLocation(37, 12);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsButton3);
        _nsBox10.setSize(450, 187);
        _nsBox10.setLocation(11, 183);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsBox10, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox9.add(_nsBox10);
        _nsBox12.setSize(450, 361);
        _nsBox12.setLocation(11, 374);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsBox12, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox9.add(_nsBox12);
        if (!(_nsBox8.getLayout() instanceof EOViewLayout)) { _nsBox8.setLayout(new EOViewLayout()); }
        _nsBox9.setSize(474, 742);
        _nsBox9.setLocation(2, 15);
        ((EOViewLayout)_nsBox8.getLayout()).setAutosizingMask(_nsBox9, EOViewLayout.MinYMargin);
        _nsBox8.add(_nsBox9);
        _nsBox8.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Page Instances", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsBox8.setSize(478, 759);
        _nsBox8.setLocation(10, 11);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsBox8, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView1.add(_nsBox8);
        _nsView1.setSize(498, 780);
        _eoFrame1.setTitle("Page Instances Inspector");
        _eoFrame1.setLocation(641, 54);
        _eoFrame1.setSize(498, 780);
        _nsTextView0.setEditable(true);
        _nsTextView0.setOpaque(true);
        _nsTextView0.setText("");
        if (!(_nsBox7.getLayout() instanceof EOViewLayout)) { _nsBox7.setLayout(new EOViewLayout()); }
        _nsTextView0.setSize(488, 623);
        _nsTextView0.setLocation(14, 14);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsTextView0);
        if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
        _nsBox7.setSize(518, 648);
        _nsBox7.setLocation(2, 15);
        ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
        _nsBox6.add(_nsBox7);
        _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Page Template", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsSearchField1, "Lucida Grande", 13, Font.PLAIN);
        _nsSearchField1.setEditable(true);
        _nsSearchField1.setOpaque(true);
        _nsSearchField1.setText("");
        _nsSearchField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsSearchField1.setSelectable(true);
        _nsSearchField1.setEnabled(true);
        _eoTableColumn2.setMinWidth(34);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(394);
        _eoTableColumn2.setWidth(394);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Name");
        if ((_eoTableColumn2.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn2.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView1.table().addColumn(_eoTableColumn2);
        _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView1.table().setRowHeight(20);
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsTableView1.setSize(400, 211);
        _nsTableView1.setLocation(14, 44);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox5.add(_nsTableView1);
        _nsSearchField1.setSize(182, 22);
        _nsSearchField1.setLocation(233, 14);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsSearchField1, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox5.add(_nsSearchField1);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(430, 266);
        _nsBox5.setLocation(2, 15);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Pages", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsSearchField0, "Lucida Grande", 13, Font.PLAIN);
        _nsSearchField0.setEditable(true);
        _nsSearchField0.setOpaque(true);
        _nsSearchField0.setText("");
        _nsSearchField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsSearchField0.setSelectable(true);
        _nsSearchField0.setEnabled(true);
        _eoTableColumn1.setMinWidth(63);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(180);
        _eoTableColumn1.setWidth(180);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Instance ID");
        if ((_eoTableColumn1.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn1.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn0.setMinWidth(79);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(196);
        _eoTableColumn0.setWidth(196);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Instance Class");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _nsTableView0.table().addColumn(_eoTableColumn0);
        _nsTableView0.table().addColumn(_eoTableColumn1);
        _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
        _nsTableView0.table().setRowHeight(20);
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController0, "add", _nsButton1), ""));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController0, "remove", _nsButton0), ""));
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(83, 26);
        _nsButton0.setLocation(245, 223);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton0);
        _nsButton1.setSize(83, 26);
        _nsButton1.setLocation(335, 223);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton1);
        _nsTableView0.setSize(400, 160);
        _nsTableView0.setLocation(14, 45);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsBox3.add(_nsTableView0);
        _nsSearchField0.setSize(182, 22);
        _nsSearchField0.setLocation(233, 15);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsSearchField0, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsBox3.add(_nsSearchField0);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(428, 256);
        _nsBox3.setLocation(2, 15);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Shared Instances", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField3, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField3.setEditable(false);
        _nsTextField3.setOpaque(true);
        _nsTextField3.setText("");
        _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField3.setSelectable(true);
        _nsTextField3.setEnabled(true);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Path:");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(true);
        _nsTextField1.setText("");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(true);
        _nsTextField1.setEnabled(true);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Name:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(64, 17);
        _nsTextField0.setLocation(-10, 15);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField0);
        _nsTextField1.setSize(162, 22);
        _nsTextField1.setLocation(59, 12);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField1);
        _nsTextField2.setSize(64, 17);
        _nsTextField2.setLocation(-10, 45);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField2);
        _nsTextField3.setSize(350, 22);
        _nsTextField3.setLocation(59, 42);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField3);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(428, 84);
        _nsBox1.setLocation(2, 15);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Module", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(432, 101);
        _nsBox0.setLocation(10, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsBox2.setSize(432, 273);
        _nsBox2.setLocation(10, 119);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsBox2);
        _nsBox4.setSize(434, 283);
        _nsBox4.setLocation(10, 396);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsBox4);
        _nsBox6.setSize(522, 665);
        _nsBox6.setLocation(451, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox6);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(983, 689);
            _eoFrame0.setTitle("Window");
            _eoFrame0.setLocation(13, 268);
            _eoFrame0.setSize(983, 689);
        }
    }
}
