--- 
:type: widget
:name: app:http
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ rest, network ]
:description: "app:http is a non-visual control for executing REST-style services"
